### ISSUE TITLE
Mod doesn't work at all on newer NVidia drivers

### ISSUE THREAD

**Issue by forkerer** [ThirteenAG/III.VC.SA.WindowedMode#13]
I was using it for few weeks on my notebook with GTX 960M without issues, not sure on what drivers version, but it must have been pretty old. After updating drivers to newest ones today, the game doesn't load at all, something must have changed that breaks this mod. I can't get it to work on my PC with GTX1660 too, it's using recent drivers too.

Currently installed drivers version on my notebook is 460.89
Game loads fine without the windowed mod, other windowed mods work good too, it's just this one

**Comment by ThirteenAG** [comment]
Works for me, I dunno. Try deleting set file.

**Comment by forkerer** [comment]
Deleting set file helped me on my notebook, i guess it should work on the PC too, thanks for quick help, I'm closing the issue :)
