### ISSUE TITLE
Black screen with Trails on/Black sky with SkyGFX installed

### ISSUE THREAD

**Issue by ZachFett** [ThirteenAG/III.VC.SA.WindowedMode#16]
If I try to turn Trails on while using this, my screen is black (other than HUD) even though I can still run around and hear sounds. Menus still work.

If I disable Trails but have the latest version of SkyGFX installed, the sky is always black.
![20211025230840_1](https://user-images.githubusercontent.com/29797689/138827410-3f3feb39-7331-4854-9b94-a2df4de695d6.jpg)

**Comment by ellie12134** [comment]
Sadly that didn't fix it for me on III
